<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Contracts' => 'Договоры',
  'contract' => 'договор',
  'Contract number' => 'Договор номер: ',
  'Create contract' => 'Создать договор',
  'Update contract' => 'Редактировать договор: ',
  'Client ID'=>'ID клиента',
  'Client'=>'Клиент',
  'Print act'=>'Печать акта',
  'Employee ID'=>'Сотрудник',
  'Number'=>'Номер договора',
  'Created At'=>'Создан',
  'Update'=>'Редактировать',
  'Create'=>'Создать',
  'Select client'=>'-Выберите клиента-',
  'Select contract' => 'Выберите договор',
  'Balance' => 'Баланс',
  'Date start'=>'Дата начала',
  'Date stop'=>'Дата окончания',
  'All clients payments'=>'Обороты клиентов за период',
  'Select date range' => 'Выберите период',
  'Get' => 'Выбрать',
  'Summ' => 'Сумма',
  '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => 'Значение «{attribute}» должно содержать {length, number} {length, plural, one{символ} few{символа} many{символов} other{символа}}.',
);
