<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Name'=>'Имя',
    'Register Address'=>'Юридический адрес',
    'Chief Name'=>'ФИО директора',
    'Glbuh Name'=>'ФИО гл. бухгалтера',
    'Check Buh Name'=>'ФИО бух. проверяющеко с\ф',
    'Bank Name'=>'Банк',
    'Bank Code'=>'МФО',
    'Payment Account'=>'Расчетный счет',
    'Unp'=>'УНН',
    'Okpo'=>'ОКПО',
    'Telephone'=>'Телефон',
    'Fax'=>'Факс',
    'Email'=>'E-mail'
);
