<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Clients' => 'Клиенты',
    'Create payment' => 'Создать платеж',
    'Contract ID' => 'Номер договора',
    'Details' => 'Сведения',
    'Show Payments'=>'Платежи',
    'Select contract to show payments'=>'Выберите договор, чтобы показать платежи',
    'Payment Sum'=>'Сумма платежа',
    'Created At'=>'Добавлено',
    'Updated At'=>'Изменено',
    'Invoice Summ'=>"Cумма счета",
    'Create invoice'=>"Создать счет-фактуру",
    'View invoice'=>"Показать счет-фактуру",
    'active'=>'Активный',
    'status'=>'Статус',
    'nonactive'=>'Не активный',
    'Save'=>'Сохранить'
);
