<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Tickets' => 'Талоны',
    'Show Tickets'=>"Показать талоны",
    'Ticket count'=>"Количество талонов",
    'Tickets saved'=>"Талоны сохранены",
    'Act date range'=>"Выберите период формирования акта",
    'Form act'=>"Сформировать акт",
    'Create ticket'=>"Создать талоны",
    'Save Ticket'=>"Сохранить талон",
    'Created At'=>"Создан",
    'Closed At'=>"Закрыт",
    'Closed'=>"Закрытые",
    'not Closed'=>"Не закрытые",
    'Close ticket'=>"Закрыть талон",
    'Save and print'=>'Сохранить и распечатать',
    'Ticket saved'=>'Талон Сохранен',
    'Select office'=>'Выберите филиал',
    'Office'=>'Филиал',
    'Services'=>'Услуги',
    'Select service'=>'Выберите услугу',
    'Services List'=>'Услуги',
);
