<?php
/**
 * Created by PhpStorm.
 * User: victor
 * Date: 02.08.16
 * Time: 16:00
 */

namespace app\components;


class Formatter extends \yii\i18n\Formatter
{
    public function asDecimal($value, $decimals = null, $options = [], $textOptions = [])
    {
        return parent::asDecimal(str_replace(',', '.', $value), $decimals, $options, $textOptions); // TODO: Change the autogenerated stub
    }

}